### ISSUE TITLE
Links von rubydoc auf github stimmen nicht

### ISSUE THREAD

**Issue by kwollw** [CAU-Kiel-Tech-Inf/client-ruby#13]
In rubydoc finden sich unter den Instance Attribute und Methods Details links wie:
[View on GitHub] https://github.com/CAU-Kiel-Tech-Inf/socha_ruby_client/blob/GameState/lib/software_challenge_client/game_state.rb#L24

Diese führen nicht auf die gewünschte Seite.

Kai Wollweber

**Comment by SKoschnicke** [comment]
Sie meinen auf der auf rubydoc gehosteten Documentation (z.B. https://www.rubydoc.info/gems/software_challenge_client/GameState#initialize-instance_method). Ich kann dort leider nirgendwo solche Links auf GitHub entdecken.

**Comment by kwollw** [comment]
vergleiche:

(1) https://www.rubydoc.info/github/CAU-Kiel-Tech-Inf/socha_ruby_client/GameState#initialize-instance_method

(2) https://www.rubydoc.info/gems/software_challenge_client/GameState#initialize-instance_method

Wir benutzen als Einstiegs-Bookmark zur Dokumentation
https://www.rubydoc.info/github/CAU-Kiel-Tech-Inf/socha_ruby_client/index
und kommen darüber auf den 1. Link.

Kai Wollweber

**Comment by SKoschnicke** [comment]
Das scheint ein Problem von RubyDoc/Yard zu sein:

- https://github.com/docmeta/rubydoc.info/issues/91
- https://github.com/docmeta/rubydoc.info/pull/103

Es funktioniert, wenn man den Branch mit angibt, also https://www.rubydoc.info/github/CAU-Kiel-Tech-Inf/socha_ruby_client/master/GameState#initialize-instance_method (man beachte das "master" am Ende)

Wo kommt denn dieser RubyDoc-GitHub-Link ueberhaupt her?
