### ISSUE TITLE
Effizienz von GameRuleLogic.possible_moves_for_shape﻿

### ISSUE THREAD

**Issue by kwollw** [CAU-Kiel-Tech-Inf/client-ruby#33]
In der Methode GameRuleLogic.possible_moves_for_shape﻿
wird über alle Felder und alle unique transforms der shapes iteriert. Warum dann noch einmal über alle piece.coords?

Liegt das daran, dass mit valid_fields(gamestate) nur eine Auswahl von Feldern untersucht wird und nicht alle Felder des boards? Dann wäre mein Einwand eventuell falsch.

```ruby
  def self.possible_moves_for_shape(gamestate, shape, fields = valid_fields(gamestate))
    color = gamestate.current_color
    moves = Set[]
    fields.each do |field|
      shape.unique_transforms().each do |t|
        piece = Piece.new(color, shape, t.r, t.f, Coordinates.new(0, 0))
        piece.coords.each do |pos| #<< ???
          moves << SetMove.new(Piece.new(color, shape, t.r, t.f, Coordinates.new(field.x - pos.x, field.y - pos.y)))
        end
      end
    end
    moves.select { |m| valid_set_move?(gamestate, m) }.to_a
  end
```
IMHO reicht:
```ruby 
fields.each do |field|
  shape.unique_transforms().each do |t|
    moves << SetMove.new(Piece.new(color, shape, t.r, t.f, field))
  end
end
```

**Comment by anarchuser** [comment]
`valid_fields` gibt alle Felder zurück, die an die gegebene Farbe anecken, aber nicht angrenzen. Die Idee ist, dass nicht über alle Felder via Brute Force iteriert wird, sondern nur über solche, auf denen ein Stein legal platziert werden kann (da jeder Stein einen anderen über Ecke berühren muss).

Demnach wird im zweiten Schritt für jede Variation geprüft, ob eine ihrer Koordinaten auf einem der validen Felder liegt.
